import "@/globals.css";
import { ReduxProvider } from "./_lib/store/ReduxProvider";
import QueryProvider from "@/_lib/QueryProvider";
import { Bounce, ToastContainer } from "react-toastify";

export const metadata = {
  title: "RV",
  description: "Generated by Next.js",
};

export default function Root({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#0a1024]">
        <QueryProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </QueryProvider>
        {/* toast container */}
        <ToastContainer
          className="z-999"
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
